APPVER = 1.0.0

NAME  = demo

OBJS += demo.o

OBJS += ../bwallet-crypto/bignum.o
OBJS += ../bwallet-crypto/bip32.o
OBJS += ../bwallet-crypto/ecdsa.o
OBJS += ../bwallet-crypto/hmac.o
OBJS += ../bwallet-crypto/ripemd160.o
OBJS += ../bwallet-crypto/secp256k1.o
OBJS += ../bwallet-crypto/sha2.o
OBJS += ../bwallet-crypto/bip39.o
OBJS += ../bwallet-crypto/pbkdf2.o

include ../Makefile.include
